[build]
  # No build command needed for static site
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# Redirect rules
[[redirects]]
  from = "/omvp/*"
  to = "/omvp/:splat"
  status = 200

[[redirects]]
  from = "/lead-magnet/*"
  to = "/omvp/lead-magnet/:splat"
  status = 200

# SPA fallback for any client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"