[build]
  # No build command needed for static site
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# Clean URL routing for new funnel structure
# 48-hour-worksheet clean URLs
[[redirects]]
  from = "/48-hour-worksheet"
  to = "/48-hour-worksheet/index.html"
  status = 200

[[redirects]]
  from = "/48-hour-worksheet/success"
  to = "/48-hour-worksheet/success.html"
  status = 200

[[redirects]]
  from = "/48-hour-worksheet/worksheet"
  to = "/48-hour-worksheet/worksheet.html"
  status = 200

# OMVP service clean URLs
[[redirects]]
  from = "/omvp"
  to = "/omvp/index.html"
  status = 200

[[redirects]]
  from = "/omvp/submit"
  to = "/omvp/submit.html"
  status = 200

[[redirects]]
  from = "/omvp/success"
  to = "/omvp/success.html"
  status = 200

[[redirects]]
  from = "/omvp/upsell"
  to = "/omvp/upsell.html"
  status = 200

# Legacy redirects for old structure
[[redirects]]
  from = "/lead-magnet/*"
  to = "/48-hour-worksheet/:splat"
  status = 301

[[redirects]]
  from = "/dojjjo-landing.html"
  to = "/index.html"
  status = 301

# Main landing page (now using index.html)
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Fallback for any other 404s (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"